# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.CharField(max_length=140, unique=True)),
                ('in_menu', models.BooleanField(default=False)),
                ('in_footer', models.BooleanField(default=False)),
                ('weight_menu', models.IntegerField(blank=True, null=True)),
                ('weight_footer', models.IntegerField(blank=True, null=True)),
                ('lang', models.IntegerField(choices=[(0, b'Spanish'), (1, b'English')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=140, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=140)),
                ('solution', models.CharField(choices=[(b'estudios-mercado', b'es - estudios-mercado'), (b'sondeos-opinion-publica', b'es - sondeos-opinion-publica'), (b'asesoria-mercadotecnia', b'es - asesoria-mercadotecnia'), (b'hispanic-market-research', b'es - hispanic-market-research'), (b'apoyo-logistico-campo', b'es - apoyo-logistico-campo'), (b'productos-focus', b'es - productos-focus'), (b'market-studies', b'en - estudios-mercado'), (b'public-opinion-polls', b'en - sondeos-opinion-publica'), (b'marketing-advisory', b'en - asesoria-mercadotecnia'), (b'hispanic-market-research2', b'en - hispanic-market-research'), (b'field-logistical-support', b'en - apoyo-logistico-campo'), (b'focus-products', b'en - productos-focus')], default=0, max_length=140)),
                ('lang', models.IntegerField(choices=[(0, b'Spanish'), (1, b'English')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Section'),
        ),
    ]
